#!/bin/bash

# Usage:
#   ./contract-to-flow contract-file [ model-file [ fe ] ]
# e.g.
#   ./contract-to-flow contract/sample-contract.json

if [ -d "$HOME/fabric-chaincode/work" ]; then
  rm -Rf $HOME/fabric-chaincode/work
fi
mkdir -p $HOME/fabric-chaincode/work

src=$WORK/$1
cp $src $HOME/fabric-chaincode/work
contract=${src##*/}
if [ "$#" -gt 1 ] && [ ! -z "$2" ]; then
  model=$2
else
  model="${contract%.*}_flow.json"
fi
fe=""
if [ "$#" -gt 2 ] && [ ! -z "$3" ]; then
  fe="-e"
fi

cd $HOME/fabric-chaincode/work
flogo contract2flow $fe -c $contract -o $model

if [ -f $model ]; then
  cp $model $(dirname $src)
else
  echo "failed to generate flogo model"
  exit 1
fi
